apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: .5Gi
            cpu: 500m
          limits:
            memory: .5Gi
            cpu: 500m
        env:
        - name: SECRET_SAUCE
          valueFrom:
            secretKeyRef:
              key: secretSauce
              name: demo-secrets
              optional: false
            