apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream # This name is fixed. Please do not change it.
  labels:
    app: ingress-upstream
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443